package provider

import (
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/apimachinery/pkg/runtime/schema"
	k8stypes "k8s.io/apimachinery/pkg/types"
)

// Type identifies the controller that owns certificate configuration.
type Type string

const (
	// OpenShift uses the OpenShift Service CA annotations.
	OpenShift Type = "openshift"
	// CertManager uses cert-manager Certificate and cainjector resources.
	CertManager Type = "cert-manager"
)

// WebhookKind identifies a supported admission webhook configuration.
type WebhookKind string

const (
	WebhookKindMutating   WebhookKind = "MutatingWebhookConfiguration"
	WebhookKindValidating WebhookKind = "ValidatingWebhookConfiguration"
)

// WebhookReference identifies an admission webhook configuration. EntryNames
// can restrict validation to named entries, but provider annotations apply to
// the whole configuration and therefore still require all entries to use the
// configured Service.
type WebhookReference struct {
	Kind       WebhookKind
	Name       string
	EntryNames []string
}

// IssuerRef identifies a cert-manager Issuer or ClusterIssuer.
type IssuerRef struct {
	Name  string
	Kind  string
	Group string
}

// CertificateSpec describes a Certificate object generated by cert-manager.
type CertificateSpec struct {
	Name      string
	IssuerRef IssuerRef
	DNSNames  []string
}

// CertificateSource selects an existing Certificate or asks the provider to
// generate one. Exactly one source is required for cert-manager targets.
type CertificateSource struct {
	ExistingRef *k8stypes.NamespacedName
	Generated   *CertificateSpec
}

// WorkloadOptions controls serving Secret patches on pod-template workloads.
type WorkloadOptions struct {
	// Selector matches workload metadata labels in the Service namespace.
	Selector labels.Selector
	// Kinds defaults to Deployment, StatefulSet, and DaemonSet.
	Kinds []schema.GroupKind
	// ContainerSelector selects containers by name. If it is nil or matches no
	// containers, all regular and init containers are selected.
	ContainerSelector func(string) bool
	MountPath         string
	VolumeName        string
}

// Target describes one Service, its admission webhooks, and its serving
// workload configuration.
type Target struct {
	Service     k8stypes.NamespacedName
	SecretName  string
	Webhooks    []WebhookReference
	Workload    WorkloadOptions
	Certificate CertificateSource
}

// DefaultWorkloadKinds returns the default supported pod-template workload kinds.
func DefaultWorkloadKinds() []schema.GroupKind {
	return []schema.GroupKind{
		{Group: "apps", Kind: "Deployment"},
		{Group: "apps", Kind: "StatefulSet"},
		{Group: "apps", Kind: "DaemonSet"},
	}
}
